from .funnyshortjokes import FunnyShortJokesScraper
from .hf1 import HF1Scraper
from .hf2 import HF2Scraper
from .hf3 import HF3Scraper
from .hf4 import HF4Scraper
from .hf5 import HF5Scraper
from .hf6 import HF6Scraper
from .hf7 import HF7Scraper
from .hf8 import HF8Scraper
from .hf9 import HF9Scraper
from .hf10 import HF10Scraper
from .hf11 import HF11Scraper
from .hf12 import HF12Scraper
from .hf13 import HF13Scraper
from .laughfactory import LaughFactoryScraper
