name: scraper
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.11
      uses: actions/setup-python@v1
      with:   
        python-version: 3.11

    - name: run_script
      run: bash depbot/scripts/run.bash
    

    